language: node_js
env:
  - IMAGE_NAME=cheney/${TRAVIS_BUILD_DIR##*/} #镜像名称与当前目录名称一致
services:
  - docker
#指定分支
branches:
  only:
  - master
#执行构建
script:
  - docker build -t $IMAGE_NAME ./
#推送至DockerHub
after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $IMAGE_NAME

  