version: '3'
#服务集合
services:
  #Docker管理可视化服务
  # visualizer:
  #   image: dockersamples/visualizer:latest
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - overlay
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #Docker集群可视化服务
  portainer:
    image: portainer/portainer:latest
    command: ["-H", "unix:///var/run/docker.sock", "--no-auth"]
    ports:
      - "9090:9000"
    networks:
      - overlay
    volumes:
      - portainer:/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #WEB服务代理
  envoy:
    image: cheney/envoy:latest
    ports:
      - '9091:9901'
      - '10000:10000'
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #服务发现
  consul-client: &consul
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}' -ui"
    depends_on:
      - consul-server-bootstrap
    deploy:
      replicas: 2
  consul-server:
    <<: *consul
    depends_on:
      - consul-server-bootstrap
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
  consul-server-bootstrap:
    image: consul:latest
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect 1 -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      placement:
        constraints: [node.role == manager]
  #自定义RPC服务
  x-grpc:
    image:  cheney/x-grpc:latest
    ports:
      - "50051:50051"
    networks:
      - overlay
    deploy:
      replicas: 1
#卷集合
volumes:
  portainer:
#网络集合
networks:
  overlay: