version: '3.7'
#服务集合
services:
  #Docker管理可视化服务
  # visualizer:
  #   image: dockersamples/visualizer:latest
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - n1_overlay
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #Docker集群可视化服务
  portainer:
    image: portainer/portainer:latest
    command: ["-H", "unix:///var/run/docker.sock", "--no-auth"]
    ports:
      - "9090:9000"
    networks:
      - n1_overlay
    volumes:
      - portainer:/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #WEB服务代理
  envoy:
    image: cheney/envoy:latest
    ports:
      - '9091:9901'
      - '10000:10000' #代理grpc-web
      - '10001:10001' #代理rabbitmq
    networks:
      - n1_overlay
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #服务发现
  consul:
    image: consul:latest
    ports:
      - target: 8500
        published: 9092
        mode: host
    networks:
      n1_overlay:
        aliases:
          - consul.cluster
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul.cluster
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
  #自定义RPC服务
  x-grpc:
    image: cheney/x-grpc:latest
    ports:
      - "50051:50051"
    networks:
      - n1_overlay
    deploy:
      replicas: 1
#卷集合
volumes:
  portainer:
#网络集合
networks:
  n1_overlay:
    external: true