version: '3'
#服务集合
services:
  #Docker管理可视化服务
  # visualizer:
  #   image: dockersamples/visualizer:latest
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - overlay
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #Docker集群可视化服务
  portainer:
    image: portainer/portainer:latest
    command: ["-H", "unix:///var/run/docker.sock", "--no-auth"]
    ports:
      - "9090:9000"
    networks:
      - overlay
    volumes:
      - portainer:/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #WEB服务代理
  envoy:
    image: cheney/envoy:latest
    ports:
      - '9091:9901'
      - '10000:10000'
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #服务发现
  consul:
    image: consul:latest
    ports:
      # - 8300:8300 #server rpc address
      # - 8301:8301 #CLuster Serf Addr LAN
      # - 8301:8301/udp
      # - 8302:8302 #Cluster Serf Addr WAN
      # - 8302:8302/udp
      # - 8400:8400 #cli rpc endpoint
      - 8500:8500 #Web UI, http api
      # - 8600:53/udp #DNS服务
    networks:
      - overlay
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=n1_consul
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #自定义RPC服务
  x-grpc:
    image:  cheney/x-grpc:latest
    ports:
      - "50051:50051"
    networks:
      - overlay
    deploy:
      replicas: 1
#卷集合
volumes:
  portainer:
#网络集合
networks:
  overlay: