version: '3'

services:

  envoy: #WEB代理服务
    image: cheney/envoy:latest
    ports:
      - '8080:8080'
      - '9901:9901'
    networks:
      - server-net

  x-grpc: #x-grpc服务
    image: cheney/x-grpc:latest
    ports:
      - '9090:9090'
    networks:
      - server-net

networks:
  server-net: