version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - x-grpc_overlay
#网络集合
networks:
  x-grpc_overlay:
    external: true