version: '3.7'
services:
  #服务发现
  consul:
    image: consul:latest
    ports:
      - target: 8500
        published: 9092
        mode: host
    networks:
      amqp:
        aliases:
          - amqp.cluster
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=amqp.cluster
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
      # placement:
      #   constraints: [node.role == manager]
        # restart_policy:
        #     condition: on-failure
        #     delay: 5s
        #     max_attempts: 3
        #     window: 120s
        # update_config:
        #     parallelism: 1
        #     delay: 10s
        #     failure_action: continue
  #消息队列服务
  # rabbitmq:
  #   image: cheney/rabbitmq-consul:latest
  #   ports:
  #     # - target: 15672
  #     #   published: 9093
  #     #   mode: host
  #     # - target: 5672
  #     #   published: 5672
  #     #   mode: host
  #     - "9093:15672"
  #     - "5672:5672"
  #     # - "25672:25672"
  #     # - "15671:15671"
  #     # - "4369:4369"
  #     # - "5671:5671"
  #   networks:
  #     - amqp
  #     # amqp:
  #     #   aliases:
  #     #     - amqp.mq.cluster
  #   environment:
  #     - 'CONSUL_HOST=amqp.cluster' #consul的集群网络地址
  #     - 'CONSUL_PORT=8500'
  #     - 'CONSUL_SVC=rabbitmq'
  #     - 'CONSUL_SVC_ADDR_AUTO=true'
  #     - 'CLEANUP_WARN_ONLY=false'
  #     - 'AUTOCLUSTER_TYPE=consul'
  #     - 'AUTOCLUSTER_CLEANUP=true'
  #     - 'RABBIMQ_ERLANG_COOKIE=secrect'
  #     - 'RABBITMQ_USE_LONGNAME=true'
  #     # - 'RABBITMQ_DEFAULT_VHOST=/'
  #     # - 'RABBITMQ_DEFAULT_USER=admin'
  #     # - 'RABBITMQ_DEFAULT_PASS=123456'
  #   deploy:
  #     # endpoint_mode: dnsrr
  #     replicas: 1
  #     # restart_policy:
  #     #     condition: on-failure
  #     #     delay: 15s
  #     #     max_attempts: 3
  #     #     window: 120s
  #     # update_config:
  #     #     parallelism: 2
  #     #     delay: 20s
  #     #     failure_action: continue
#网络集合
networks:
  amqp:
    external: true